//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlparMoto_IMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Part_Number { get; set; }
        public string Product_Name { get; set; }
        public double Stock_Amount { get; set; }
        public string Description { get; set; }
        public string Keywords { get; set; }
        public System.DateTime Date_Received { get; set; }
        public double Price { get; set; }
        public double Retail_Price { get; set; }
        public System.DateTime Time_Date_Added { get; set; }
    }
}
