//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlparMoto_IMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_change
    {
        public int ChangeID { get; set; }
        public int UserID { get; set; }
        public string Name { get; set; }
        public string Change { get; set; }
        public System.DateTime Time_Date_of_Change { get; set; }
    }
}
